spring:
  config:
    activate:
      on-profile: migration-test
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_MIGRATION_USERNAME}
    password: ${DB_MIGRATION_PASSWORD}
    clean-disabled: true
    baseline-on-migrate: false
    out-of-order: false
    validate-on-migrate: true

ridervoice:
  auth:
    oauth2:
      kakao:
        client-id: migration-test-client
  restaurant:
    kakao-local:
      api-key: migration-test-key
